/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "sigs.k8s.io/multi-network-api/apis/v1alpha1"
	scheme "sigs.k8s.io/multi-network-api/pkg/client/clientset/versioned/scheme"
)

// PodNetworkListsGetter has a method to return a PodNetworkListInterface.
// A group's client should implement this interface.
type PodNetworkListsGetter interface {
	PodNetworkLists() PodNetworkListInterface
}

// PodNetworkListInterface has methods to work with PodNetworkList resources.
type PodNetworkListInterface interface {
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PodNetworkList, error)
	PodNetworkListExpansion
}

// podNetworkLists implements PodNetworkListInterface
type podNetworkLists struct {
	*gentype.Client[*v1alpha1.PodNetworkList]
}

// newPodNetworkLists returns a PodNetworkLists
func newPodNetworkLists(c *MultinetworkV1alpha1Client) *podNetworkLists {
	return &podNetworkLists{
		gentype.NewClient[*v1alpha1.PodNetworkList](
			"podnetworklists",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.PodNetworkList { return &v1alpha1.PodNetworkList{} }),
	}
}
