/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1alpha1 "sigs.k8s.io/multi-network-api/apis/applyconfiguration/apis/v1alpha1"
	v1alpha1 "sigs.k8s.io/multi-network-api/apis/v1alpha1"
	scheme "sigs.k8s.io/multi-network-api/pkg/client/clientset/versioned/scheme"
)

// PodNetworksGetter has a method to return a PodNetworkInterface.
// A group's client should implement this interface.
type PodNetworksGetter interface {
	PodNetworks() PodNetworkInterface
}

// PodNetworkInterface has methods to work with PodNetwork resources.
type PodNetworkInterface interface {
	Create(ctx context.Context, podNetwork *v1alpha1.PodNetwork, opts v1.CreateOptions) (*v1alpha1.PodNetwork, error)
	Update(ctx context.Context, podNetwork *v1alpha1.PodNetwork, opts v1.UpdateOptions) (*v1alpha1.PodNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podNetwork *v1alpha1.PodNetwork, opts v1.UpdateOptions) (*v1alpha1.PodNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PodNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PodNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PodNetwork, err error)
	Apply(ctx context.Context, podNetwork *apisv1alpha1.PodNetworkApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.PodNetwork, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, podNetwork *apisv1alpha1.PodNetworkApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.PodNetwork, err error)
	PodNetworkExpansion
}

// podNetworks implements PodNetworkInterface
type podNetworks struct {
	*gentype.ClientWithListAndApply[*v1alpha1.PodNetwork, *v1alpha1.PodNetworkList, *apisv1alpha1.PodNetworkApplyConfiguration]
}

// newPodNetworks returns a PodNetworks
func newPodNetworks(c *MultinetworkV1alpha1Client) *podNetworks {
	return &podNetworks{
		gentype.NewClientWithListAndApply[*v1alpha1.PodNetwork, *v1alpha1.PodNetworkList, *apisv1alpha1.PodNetworkApplyConfiguration](
			"podnetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.PodNetwork { return &v1alpha1.PodNetwork{} },
			func() *v1alpha1.PodNetworkList { return &v1alpha1.PodNetworkList{} }),
	}
}
