/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/multi-network-api/apis/v1alpha1"
)

// FakePodNetworkLists implements PodNetworkListInterface
type FakePodNetworkLists struct {
	Fake *FakeMultinetworkV1alpha1
}

var podnetworklistsResource = v1alpha1.SchemeGroupVersion.WithResource("podnetworklists")

var podnetworklistsKind = v1alpha1.SchemeGroupVersion.WithKind("PodNetworkList")

// Get takes name of the podNetworkList, and returns the corresponding podNetworkList object, and an error if there is any.
func (c *FakePodNetworkLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PodNetworkList, err error) {
	emptyResult := &v1alpha1.PodNetworkList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(podnetworklistsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.PodNetworkList), err
}
